server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/srt_generator}
    username: ${DATABASE_USERNAME:srt_user}
    password: ${DATABASE_PASSWORD:srt_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
    ssl:
      trust-store-location: ${KAFKA_TRUSTSTORE_LOCATION:}
      trust-store-password: ${KAFKA_TRUSTSTORE_PASSWORD:}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
    consumer:
      group-id: java-app-results-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.soundintotext.srt_generator.domain.model"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.soundintotext.srt_generator.domain.model.SubtitleResultEvent
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
storage:
  provider: ${STORAGE_PROVIDER:local}
  local:
    base-path: ${STORAGE_BASE_PATH:/home/magan/subtitles-storage}
  r2:
    endpoint: ${R2_ENDPOINT:}
    access-key: ${R2_ACCESS_KEY:}
    secret-key: ${R2_SECRET_KEY:}
    bucket: ${R2_BUCKET:}